from contextlib import asynccontextmanager
from uuid import uuid4
import time

import joblib
import pandas as pd
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

from app.logging_config import setup_logging
from app.models.schemas import PredictionInput, PredictionOutput


model = None

logger = setup_logging()


class PredictionError(Exception):
    pass


@asynccontextmanager
async def lifespan(app: FastAPI):
    global model

    model = joblib.load("ml/saved_model/model.joblib")

    logger.info("RandomForest model loaded successfully!")

    yield


app = FastAPI(lifespan=lifespan)


# ---------------------------------------------------------
# Task 9 - Step 2 & Step 3
# Request Logging Middleware
# ---------------------------------------------------------

@app.middleware("http")
async def log_requests(request: Request, call_next):
    # Generate a unique request ID for every incoming request
    request_id = str(uuid4())

    # Store request ID so endpoints can access the same ID
    request.state.request_id = request_id

    # Start timer
    start_time = time.perf_counter()

    # Process request
    response = await call_next(request)

    # Calculate request duration
    duration = time.perf_counter() - start_time

    # Log request details
    logger.info(
        f"Request | "
        f"request_id={request_id} | "
        f"method={request.method} | "
        f"path={request.url.path} | "
        f"status_code={response.status_code} | "
        f"duration={duration:.4f}s"
    )

    return response


# ---------------------------------------------------------
# Task 8 - Custom Exception Handler
# ---------------------------------------------------------

@app.exception_handler(PredictionError)
async def prediction_error_handler(
    request: Request,
    exc: PredictionError
):
    request_id = getattr(
        request.state,
        "request_id",
        "unknown"
    )

    logger.error(
        f"Prediction failed | "
        f"request_id={request_id}"
    )

    return JSONResponse(
        status_code=500,
        content={
            "detail": "Prediction failed"
        }
    )


# ---------------------------------------------------------
# Root Endpoint
# ---------------------------------------------------------

@app.get("/")
def root():
    return {
        "message": "ML API is alive"
    }


# ---------------------------------------------------------
# Health Check Endpoint
# ---------------------------------------------------------

@app.get("/health")
def health():
    return {
        "status": "ok",
        "model_loaded": model is not None
    }


# ---------------------------------------------------------
# Prediction Endpoint
# ---------------------------------------------------------

@app.post("/predict", response_model=PredictionOutput)
def predict(
    data: PredictionInput,
    request: Request
):
    # Get the SAME request ID generated by middleware
    request_id = request.state.request_id

    # Convert input into DataFrame
    input_data = pd.DataFrame([{
        "sepal length (cm)": data.sepal_length,
        "sepal width (cm)": data.sepal_width,
        "petal length (cm)": data.petal_length,
        "petal width (cm)": data.petal_width,
    }])

    try:
        # Make prediction
        prediction = model.predict(input_data)

        # Default confidence
        confidence = 0.0

        # Calculate confidence if model supports predict_proba
        if hasattr(model, "predict_proba"):
            probabilities = model.predict_proba(input_data)
            confidence = float(probabilities.max())

        # Log successful prediction
        logger.info(
            f"Prediction successful | "
            f"request_id={request_id} | "
            f"prediction={int(prediction[0])}"
        )

        return {
            "prediction": int(prediction[0]),
            "confidence": confidence,
            "request_id": request_id
        }

    except Exception as exc:

        # Log actual error internally
        logger.error(
            f"Prediction error | "
            f"request_id={request_id} | "
            f"error={exc}"
        )

        # Send safe error response to client
        raise PredictionError()

